# This file is auto-generated by the dh-umc tools and should not be edited!
msgid ""
msgstr ""
"Project-Id-Version: univention-management-console-module-diagnostic\n"
"Report-Msgid-Bugs-To: packages@univention.de\n"
"POT-Creation-Date: 2017-08-01 14:44+0200\n"
"PO-Revision-Date: \n"
"Last-Translator: Univention GmbH <packages@univention.de>\n"
"Language-Team: Univention GmbH <packages@univention.de>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: umc/python/diagnostic/plugins/nameserver.py:15
#, python-format
msgid "%d of the configured nameservers are not responding to DNS queries."
msgstr "%d der konfigurierten Nameserver anworten nicht auf DNS-Anfragen."

#: umc/python/diagnostic/plugins/nameserver.py:46
msgid "A timeout occurred while reaching the nameserver (is it online?)."
msgstr ""
"Eine Zeitüberschreitung trat beim Erreichen des Nameservers auf (ist er "
"online?)."

#: umc/python/diagnostic/plugins/security_limits.py:31
msgid "Adjust to suggested limits"
msgstr "An vorgeschlagene Limits anpassen"

#: umc/python/diagnostic/plugins/check_server_password.py:150
msgid "Authentication against the local LDAP failed with the machine password."
msgstr ""
"Authentifizierung gegen das lokale LDAP mit dem Password für das "
"Rechnerkonto ist fehlgeschlagen."

#: umc/python/diagnostic/plugins/check_server_password.py:154
msgid ""
"Authentication against the master LDAP failed with the machine password."
msgstr ""
"Authentifizierung gegen das Master LDAP mit dem Password für das "
"Rechnerkonto ist fehlgeschlagen."

#: umc/python/diagnostic/plugins/check_server_password.py:53
msgid "Authentication with machine password against LDAP successful."
msgstr "Authentifizierung mit dem Password für das Rechnerkonto erfolgreich."

#: umc/python/diagnostic/plugins/check_server_password.py:111
msgid "Calling /usr/lib/univention-server/server_password_change failed."
msgstr ""
"Aufruf von /usr/lib/univention-server/server_password_change ist "
"fehlgeschlagen."

#: umc/python/diagnostic/plugins/check_server_password.py:52
msgid "Check machine password"
msgstr "Password für das Rechnerkonto testen"

#: umc/python/diagnostic/plugins/check_server_password.py:145
msgid "Fix machine password"
msgstr "Korrigiere Password für das Rechnerkonto"

#: umc/python/diagnostic/plugins/gateway.py:11
msgid "Gateway is not reachable"
msgstr "Gateway ist nicht erreichbar"

#: umc/python/diagnostic/plugins/ssh_connection.py:54
msgid "Host key for server does not match"
msgstr "SSH Host-Key des Servers stimmt nicht überein"

#: umc/python/diagnostic/plugins/nameserver.py:17
msgid ""
"If the problem persists make sure the nameserver is connected to the network "
"and the forwarders are able to reach the internet (www.univention.de)."
msgstr ""
"Falls das Problem bestehen bleibt stellen Sie sicher, dass der Nameserver "
"mit dem Netzwerk verbunden ist und die DNS-Forwarder das Internet erreichen "
"können (www.univention.de)."

#: umc/python/diagnostic/plugins/gateway.py:14
msgid "If these settings are correct the problem relies in the gateway itself:"
msgstr ""
"Wenn diese Einstellungen richtig sind liegt das Problem im Gateway selbst:"

#: umc/python/diagnostic/plugins/security_limits.py:19
#, python-brace-format
msgid ""
"It is suggested to increase the security limits either manually by using "
"{ucr} or to automatically adjust them to the suggested limits:"
msgstr ""
"Es ist empfohlen, die Sicherheitslimits entweder manuell durch benutzen des "
"{ucr} oder durch automatische Anpassung auf die empfohlenen Limits zu "
"erhöhen."

#: umc/python/diagnostic/plugins/ssh_connection.py:59
#, python-format
msgid ""
"Login to the remote server with the uid %(uid)s and the password from /etc/"
"machine.secret failed. "
msgstr ""
"Der Login auf dem entfernten Rechner mit der uid %(uid)s und dem Passwort "
"aus /etc/machine.secret is fehlgeschlagen. "

#: umc/python/diagnostic/plugins/package_status.py:14
msgid ""
"Login to the system as root via ssh and run the command \"dpkg --configure -a"
"\" in order to correct the packages status."
msgstr ""
"Um den Paketstatus zu korrigieren loggen Sie sich am System per ssh als root "
"ein und führen Sie das Kommando \"dpkg --configure -a\" aus."

#: umc/python/diagnostic/plugins/ssh_connection.py:58
msgid "Machine authentication failed"
msgstr "Authentifizierung mit dem Maschinen-Konto ist fehlgeschlagen"

#: umc/python/diagnostic/plugins/gateway.py:15
msgid "Make sure the hardware of the gateway device is working properly."
msgstr ""
"Stellen Sie sicher, dass die Hardware des Gateway-Geräts korrekt "
"funktioniert."

#: umc/python/diagnostic/plugins/package_status.py:15
msgid ""
"More information about the cause can be gained by executing \"dpkg --audit\"."
msgstr ""
"Weitere Informationen über die Ursache können durch Ausführen von \"dpkg --"
"audit\" erhalten werden."

#: umc/python/diagnostic/plugins/nameserver.py:13
msgid "Nameserver(s) are not responsive"
msgstr "Nameserver sind nicht ansprechbar"

#: umc/python/diagnostic/plugins/check_server_password.py:163
msgid ""
"Note that password rotation is disabled via the UCR variable server/password/"
"change."
msgstr ""
"Beachten Sie, dass die Passwordrotation durch die UCR Variable server/"
"password/change deaktiviert ist."

#: umc/python/diagnostic/plugins/check_server_password.py:164
msgid "Note that server/password/interval is set to {}."
msgstr "Beachten Sie, dass server/password/interval auf {} gesetzt ist."

#: umc/python/diagnostic/plugins/package_status.py:11
msgid "Package status corrupt"
msgstr "Paketstatus korrupt"

#: umc/python/diagnostic/plugins/ssh_connection.py:60
msgid ""
"Please check /var/log/auth.log on the remote server for further information."
msgstr ""
"Bitte prüfen Sie /var/log/auth.log auf dem entfernten Rechner für weitere "
"Informationen."

#: umc/python/diagnostic/plugins/nameserver.py:16
msgid ""
"Please make sure the DNS settings in the {setup:network} are correctly set "
"up."
msgstr ""
"Bitte sicherstellen, dass die DNS-Einstellungen in {setup:network} korrekt "
"konfiguriert sind."

#: umc/python/diagnostic/plugins/ssh_connection.py:56
#, python-format
msgid ""
"Please repair the host key of the remote server in /root/.ssh/known_hosts on "
"%(fqdn)s."
msgstr ""
"Der SSH Host-Key in /root/.ssh/known_hosts des entfernten Rechners muss auf "
"%(fqdn)s repariert werden."

#: umc/python/diagnostic/plugins/check_server_password.py:112
#, python-brace-format
msgid "Please see {sdb} for more information."
msgstr "Siehe {sdb} für weitere Informationen."

#: umc/python/diagnostic/plugins/proxy.py:15
msgid "Proxy server failure"
msgstr "Proxy-Server-Fehler"

#: umc/python/diagnostic/plugins/ssh_connection.py:16
msgid "SSH connection to UCS server failed!"
msgstr "SSH-Verbindung zu anderem UCS Server fehlgeschlagen!"

#: umc/python/diagnostic/plugins/security_limits.py:14
msgid "Security limits exceeded"
msgstr "Sicherheitslimits überschritten"

#: umc/python/diagnostic/plugins/check_server_password.py:167
#, python-brace-format
msgid "See {sdb} for information on manual server password change."
msgstr ""
"Siehe {sdb} für weitere Informationen für einen manuellen Tausch des "
"Passwords für das Rechnerkonto."

#: umc/python/diagnostic/plugins/check_server_password.py:174
msgid "Set server/password/change=True"
msgstr "Setze server/password/change=True"

#: umc/python/diagnostic/plugins/check_server_password.py:180
msgid "Set server/password/interval=21"
msgstr "Setze server/password/interval=21"

#: umc/python/diagnostic/__init__.py:280
msgid "Test again"
msgstr "Erneut testen"

#: umc/python/diagnostic/plugins/ssh_connection.py:52
msgid ""
"The following list shows the affected remote servers and the reason for the "
"failed ssh connection:"
msgstr ""
"Die folgende Liste zeigt die betroffenen entfernten Rechner und den Grund "
"für die fehlgeschlagene SSH-Verbindung."

#: umc/python/diagnostic/plugins/gateway.py:13
#, python-format
msgid ""
"The gateway %r could not be reached. Please make sure the gateway and "
"related network settings are correctly configured by using the {setup:"
"network}."
msgstr ""
"Das gateway %r konnte nicht erreicht werden. Bitte durch Benutzung des "
"{setup:network} sicherstellen, dass Gateway- und zusammengehörige "
"Netzwerkeinstellungen korrekt konfiguriert sind."

#: umc/python/diagnostic/plugins/proxy.py:69
msgid ""
"The hostname of the proxy could not be resolved. May check your DNS "
"configuration."
msgstr ""
"Der Rechnername des Proxies konnte nicht aufgelöst werden. Bitte DNS-"
"Konfiguration überprüfen."

#: umc/python/diagnostic/plugins/security_limits.py:61
msgid "The limits have been adjusted to the suggested value."
msgstr "Die Limits wurden auf die empfohlenen Werte erhöht."

#: umc/python/diagnostic/plugins/nameserver.py:43
#, python-format
msgid "The nameserver %(nameserver)s (UCR variable %(var)r) is not responsive:"
msgstr ""
"Der Nameserver %(nameserver)s (UCR Variable %(var)r) ist nicht ansprechbar:"

#: umc/python/diagnostic/plugins/package_status.py:13
#, python-format
msgid "The package status of %s packages is corrupt."
msgstr "Der Paketstatus von %s Paketen ist korrupt."

#: umc/python/diagnostic/plugins/proxy.py:67
#, python-format
msgid ""
"The proxy host could not be reached. Make sure that hostname (%(hostname)r) "
"and port (%(port)r) are correctly set up."
msgstr ""
"Der Proxy-Host konnte nicht erreicht werden. Bitte sicherstellen, dass "
"Rechnername (%(hostname)r) und Port (%(port)r) korrekt eingestellt sind."

#: umc/python/diagnostic/plugins/proxy.py:84
#, python-format
msgid ""
"The proxy server is reachable but the HTTP response status code (%d) does "
"not indicate success."
msgstr ""
"Der Proxy-Server ist erreichbar aber der HTTP-Antwort-Status-Code (%d) "
"besagt keinen Erfolg."

#: umc/python/diagnostic/plugins/security_limits.py:17
msgid ""
"The security limits (e.g. for max_open_files) are currently not configured "
"properly."
msgstr ""
"Die Sicherheitslimits (z.B. für max_open_files) sind derzeit nicht geeignet "
"eingestellt."

#: umc/python/diagnostic/plugins/proxy.py:71
#, python-format
msgid ""
"The server did not respond within %d seconds. Please check your network "
"configuration."
msgstr ""
"Der Server antwortete nicht innerhalb von %d Sekunden. Bitte "
"Netzwerkeinstellungen überprüfen."

#: umc/python/diagnostic/plugins/ssh_connection.py:51
msgid "The ssh connection to at least one other UCS server failed. "
msgstr ""
"Die SSH-Verbindung zu mindestens einem anderen UCS Server ist "
"fehlgeschlagen. "

#: umc/python/diagnostic/plugins/ssh_connection.py:55
msgid ""
"The ssh host key of the remote server has changed (maybe the host was "
"reinstalled). "
msgstr ""
"Der SSH Host-Key des entfernten Rechners hat sich geändert (vielleicht wurde "
"der Rechner neu installiert). "

#: umc/python/diagnostic/plugins/gateway.py:28
msgid "There is no gateway configured."
msgstr "Es ist kein Gateway eingerichtet."

#: umc/python/diagnostic/plugins/proxy.py:16
msgid ""
"There was an error using the proxy server. The {setup:network} can be used "
"to change the proxy configuration.\n"
msgstr ""
"Es gab einen Fehler beim Benutzen des Proxy-Servers. Das {setup:network} "
"kann zur Veränderung der Proxy-Konfiguration genutzt werden.\n"

#: umc/python/diagnostic/plugins/security_limits.py:18
msgid ""
"This can cause several different serious problems (e.g. the login at samba "
"servers may be impossible, file operations (copy, move) on shares can fail, "
"etc.)"
msgstr ""
"Dies kann mehrere verschiedene ernsthafte Probleme verursachen (z.B. Login "
"an Samba-Servern unmöglich, Dateioperationen (Kopieren, Verschieben) auf "
"Freigaben kann fehlschlagen, uvm.)"

#: umc/python/diagnostic/plugins/proxy.py:85
#, python-format
msgid ""
"This warning might be harmless. Nevertheless make sure the authentication "
"credentials (if any) are correct and the proxy server ACLs do not forbid "
"requests to %s."
msgstr ""
"Diese Warnung könnte harmlos sein. Trotzdem sollte sichergestellt werden, "
"dass Authentifikations-Zugangsdaten (falls existierend) korrekt sind und die "
"ACL's des Proxy-Servers nicht verbieten, Anfragen an %s zu stellen."

#: umc/python/diagnostic/plugins/check_server_password.py:75
msgid "Unable to fix machine password on {}"
msgstr ""
"Nicht im Stande das Password für das Rechnerkonto für {} zu korrigieren."

#: umc/python/diagnostic/plugins/check_server_password.py:57
msgid "Univention Support Database - Manually trigger server password change"
msgstr ""

#: umc/python/diagnostic/plugins/check_server_password.py:56
msgid ""
"http://sdb.univention.de/content/24/330/en/manually-trigger-server-password-"
"change.html"
msgstr ""

#: umc/python/diagnostic/plugins/package_status.py:28
msgid "some"
msgstr "einigen"
